[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4.1"
clap = { version = "4.5.17", features = ["derive"] }
lang = { path = "../lang"}
templating = { path = "../templating"}